### ISSUE TITLE
Don't tie in to UploadedFile

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/files#24]
This is  a **feature request**.

### Prerequisites
yes

### Description

To enhance code-reuse, and allow programmatically adding (generated) documents, don't limit the class to an Uploadedfile, but just a File.

### Use-case

a certain documentable model let's the server generate a file under certain conditions. For consistency this file should be added to the Documentable of the model.

current workaround is abusing UploadedFile's test mode

**Comment by aocneanu** [comment]
could you make a PR?

**Comment by jlsjonas** [comment]
I'll see what I can do

**Comment by jlsjonas** [comment]
There's an issue with Laravel's inheritance preventing proper implementation of this without some trust, PR with changes incoming requesting `Symfony\Component\HttpFoundation\File\File` **however** I can't force-check against it. ([php doesn't have union type hinting](https://stackoverflow.com/a/46777453/620141))

- Symfony's `UploadedFile` is correctly extending it's `File` class, so inheritance wouldn't be an issue
- Laravel's `UploadedFile` is not extending Laravel's `File` (to avoid duplicating a lot of Symfony's `UploadedFile`'s code
- Using Symfony's `File` directly would eliminate Laravel's FileHelpers trait, which would need to be manually added (notably `hashName`).

Implemented by expecting `\Symfony\Component\HttpFoundation\File\File` and checking if it's an instance of `\Illuminate\Http\UploadedFile` or `\Illuminate\Http\File` in code + type-hinting in phpDoc so most IDE's take it into account.

If you have a better implementation idea be sure to let me know.

**Comment by aocneanu** [comment]
Implemented in the v3.1

**Comment by jlsjonas** [comment]
Ok, waiting for the changelog update as it looks like quite a significant rewrite with renames.
