### ISSUE TITLE
External access of route `core.files.show` responds 404.

### ISSUE THREAD

**Issue by stotes** [laravel-enso/files#43]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
When trying to access the `core.files.show` route from an external link (not within the enso app itself) it gives a 404 not found.

```php
    public function getDocumentFileLinks()
    {
        return $this->documents->map(function ($doc) {
            if ($doc->file && $doc->file->id) {
                return route('core.files.show', $doc->file->id);
            }
        });
    }
```

### Steps to Reproduce
Open new tab/window with URL `http://enso.test/api/core/files/show/1` 

### Expected behavior
If authorised/logged-in, show the file.
### Actual behavior
404

**Comment by stotes** [comment]
I should note the exact same route/url gives the expected behaviour when in the Enso ecosystem. 
![image](https://user-images.githubusercontent.com/941055/113356686-04c74100-9386-11eb-8499-f5fbe871b89a.png)
If I click the show button, as expected it opens a `_blank` and shows the file with the url `http://enso.test/api/core/files/show/1`. However if I open a new tab and paste the url `http://enso.test/api/core/files/show/1`, I am getting a 404. 

Perhaps is this is related to rewrite rules in nginx?

**Comment by raftx24** [comment]
Hi @stotes, why don't you use `share`? 
with share, you will get signed-url and you can get it everywhere.

**Comment by stotes** [comment]
@raftx24 does `share` not expire? I need to have external access that has no expiry (perma links) for some specific files.

**Comment by aocneanu** [comment]
@stotes you can set the expiration time in config/enso/files.php (linkExpiration).

Sharing the show/download link with someone else is not intended / supported. The route is password protected anyway.

If you access the link in a new tab the frontend router will take over.
